Java 05. ДЗ 01, Стребежев Игорь
xamgore/au-java-homework pull request #1
Opened 2018-03-04 23:45 UTC by xamgore

[Ссылка на задание](https://www.dropbox.com/sh/vx5wfbjo6bk1dmd/AABHit_R2OQ78xKqHm2TjB1Va/02/Task.pdf?dl=0)

2018-03-06 20:23 UTC, dsavvinov requested changes
С точки зрения ясности кода, очень здорово.
С точки зрения именно стиля Java-кода, есть небольшие огрехи.

Жду ответа на вопросы

2018-03-06 20:23 UTC, dsavvinov commented on src/main/java/TrieImpl.java
> +  protected class Vertex {
зачем `protected`?

2018-03-06 20:23 UTC, dsavvinov commented on src/main/java/TrieImpl.java
> +    boolean isTerminal = false;
Здесь и везде далее: `package-private` visibility. Она в Java default, но в коде это нифига не разумный default, и по факту нужна она очень редко.

2018-03-06 20:23 UTC, dsavvinov commented on src/main/java/TrieImpl.java
> +    if (contains(str))
Minor: в Java-мире обычно заключают блоки в фигурные скобки, даже если блоки состоят из одного выражения.

2018-03-06 20:23 UTC, dsavvinov commented on src/main/java/TrieImpl.java
> +    for (int idx = 0; idx < str.length(); idx++) {
Уместно использовать enhanced-for: `for (char ch : str.toCharArray())`

2018-03-06 20:23 UTC, dsavvinov commented on src/main/java/TrieImpl.java
> +      return true;
Что-то напутано. Просили же возвращать `true`, если добавление было выполнено успешно, т.е. если элемент не содержался в коллекции.

2018-03-06 20:23 UTC, dsavvinov commented on src/main/java/TrieImpl.java
> +    boolean exists = cur.isTerminal;
1. Кажется, что `exists` тут всегда должен быть `false`, иначе `contains` должен был вернуть `true` и мы до сюда не дошли бы

2. Второй кусок ошибки с инвертированным выходом: если элемента не существовало, то надо возвращать `true`

2018-03-06 20:23 UTC, dsavvinov commented on src/main/java/TrieImpl.java
> +    cur.isTerminal = false;
Если мы вылетели из цикла выше по `break`, то `cur` здесь -- это совсем не та вершина, которая соответствует последней букве удаляемого слова. Кажется, что мы тут можем чего-нибудь поломать, например, в таком случае:

```
add("abc") // 'c' is terminal
add("abcdef") // 'c' and 'f' are terminal
remove("abcdef") // 'c' should remain terminal!
contains("abc") // should still return true
```

2018-03-06 20:23 UTC, dsavvinov commented on src/main/java/TrieImpl.java
> +    for (int idx = 0; idx < str.length() && cur != null; idx++)
`NullPointerException`, если `str == null`

2018-03-06 23:13 UTC, xamgore commented on src/main/java/TrieImpl.java
> +    for (int idx = 0; idx < str.length(); idx++) {
`toCharArray` будет создавать новую копию массива всякий раз. Точно такое нужно использовать?

2018-03-07 08:00 UTC, dsavvinov commented on src/main/java/TrieImpl.java
> +    for (int idx = 0; idx < str.length(); idx++) {
На самом деле нет, не будет. Можешь поверить мне на слово, а можешь попробовать доказать это самостоятельно и попробовать убедить меня -- за хороший ответ поставлю доп. баллы :)

2018-03-07 12:32 UTC, xamgore commented on src/main/java/TrieImpl.java
> +  protected class Vertex {
Я думал, что для наследников `TrieImpl` будет важно иметь возможность создавать и работать с `Vertex`, ну а для всех остальных чуваков вне пакета такое не надо разрешать. Оказалось, что из другого пакета вообще не достучаться до `protected Vertex`, даже в наследниках `TrieImpl`.

2018-03-08 05:12 UTC, xamgore commented on src/main/java/TrieImpl.java
> +    for (int idx = 0; idx < str.length(); idx++) {
![image](https://user-images.githubusercontent.com/4586392/37133913-ef8ef696-22a6-11e8-8842-f2ac6d657d71.png)

Вот декомпилированный метод, openjdk "1.8.0_144". Судя по твоему утверждению JVM / JIT должен следить, что значения в полученном массиве не изменяются, и возвращать `value` из исходной строки. Вряд ли бы таким занимался сам компилятор; если покопаться с `jitwatch`, это что-нибудь даст?

2018-03-08 05:38 UTC, xamgore commented on src/main/java/TrieImpl.java
> +    boolean isTerminal = false;
Всегда воспринимал `package-private` как "модификатор-пофиг". По сути можно написать внутри Vertex кучу `private / public` модификаторов, но я решил сделать проще: помечаем `TrieImpl` как `final`, и тогда на модификаторы внутри `Vertex` действительно становится всё равно. Так же можно делать?

2018-03-08 05:56 UTC, xamgore commented on src/main/java/TrieImpl.java
> +      return true;
Так, исправил, написал тест `testTrieAddResult`.

2018-03-08 06:24 UTC, xamgore commented on src/main/java/TrieImpl.java
> +    for (int idx = 0; idx < str.length() && cur != null; idx++)
Добавил ко всем методам проверку на невалидность (null / empty string), аннотации `@Nullable @NotNull` и соответствующий тест.

2018-03-08 06:46 UTC, xamgore commented on src/main/java/TrieImpl.java
> +    boolean exists = cur.isTerminal;
Исправил, покрыл тестом `testTrieAddResult`.

2018-03-08 07:44 UTC, xamgore commented on src/main/java/TrieImpl.java
> +    cur.isTerminal = false;
Действительно. Мне это место тоже подозрительным показалось, но я видимо, плохо поспал, и не захотел думать дальше. Исправил и написал тест `testRemoveDoesNotRemoveAnotherString`.

2018-03-11 17:20 UTC, dsavvinov commented on src/main/java/TrieImpl.java
> +  protected class Vertex {
Я не вижу очень много смысла в том, чтобы наследвать `TrieImpl`. На мой вкус, здесь было бы уместнее сделать класс финальным (правда, в Java-мире на это *очень* часто забивают, так что и от вас я этого требовать не буду)

2018-03-11 17:23 UTC, dsavvinov commented on src/main/java/TrieImpl.java
> +    boolean isTerminal = false;
Нет, не стоит.
Основная мотивация в том, что явные `private/public` разбивают класс на публичное API и приватные детали имплементации. Это очень упрощает чтение этого класса: чтобы ответить на вопрос "**что** делает этот класс?", достаточно посмотреть на публичные методы/поля, а все приватные можно просто пропускать. 
Да, писать кучу модификаторов может быть не очень приятно, но это Java, придется привыкать :)

2018-03-11 17:26 UTC, dsavvinov commented on src/main/java/TrieImpl.java
> +    for (int idx = 0; idx < str.length(); idx++) {
Нет, нужно смотреть не туда: сам по себе метод `toCharArray()` действительно честно копирует массив. На самом деле, в данном случае `toCharArray()` *вызовется* один раз -- это гарантирует семантика `enhacned-for`, прописанная в JLS.

2018-03-11 17:28 UTC, dsavvinov commented on src/main/java/TrieImpl.java
> +    boolean isTerminal = false;
"Модификатором-пофиг" должен быть на самом деле `private` :) А если он не подходит -- тогда почти наверняка `public`.

2018-03-11 17:31 UTC, dsavvinov approved these changes
После исправлений код стал ощутимо более "каноничным" :) Добавляя это к тому, что с логикой в коде изначально все было хорошо, получаем легко и приятно читаемый код. 
Отдельный плюсик за nullability-annotations.
Снимаю балл за баги с удалением слов в первой итерации. Итого 9 баллов, зачтено

2018-03-11 21:30 UTC, xamgore commented on src/main/java/TrieImpl.java
> +    for (int idx = 0; idx < str.length(); idx++) {
А, ну это итак было ясно :smile: 

Чтобы это проверить можно просто декомпилировать класс (голый байткод я уже давно не читал) и увидеть, как оно выглядит.

<img src="https://user-images.githubusercontent.com/4586392/37258660-0b7b858a-258c-11e8-9cab-d46f462d8355.png" width="350">

Видно, что один раз вызывается `toCharArray`, дальше используется обычный цикл `for`. То что это написано в JLS тоже легко гуглится, мне показалось, что вопрос был не про это совсем.

> а можешь попробовать доказать это самостоятельно и попробовать убедить меня -- за хороший ответ поставлю доп. баллы :)

Жду свой балл :smiling_imp:

2018-03-12 06:30 UTC, dsavvinov commented on src/main/java/TrieImpl.java
> +    for (int idx = 0; idx < str.length(); idx++) {
На самом деле, ответ "в байткоде так написано" неверный -- из того, что javac генерирует такой байткод, ещё не следует, что семантика enhanced-for именно такая. Это может быть какой-нибудь специфичной именно для этого случая оптимизацией например, или вообще прихотью конкретной имплементации компилятора.

Хороший и правильный ответ такой: заходим в JLS и находим секцию про enhanced-for, читаем и убеждаемся, что там все действительно так, и ссылаемся на нее.

Балла не будет :)

2018-05-26 12:01 UTC, closed without merging