Java05. ДЗ 02, Стребежев Игорь
xamgore/au-java-homework pull request #2
Opened 2018-03-28 20:34 UTC by xamgore

2018-04-16 19:03 UTC, dsavvinov requested changes
`shrink()` надо чинить

2018-04-16 19:03 UTC, dsavvinov commented on src/main/java/au/xamgore/HashDict.java
> +    if (oldBuckets == null || !moveOld) {
Мне кажется, `oldBuckets == null` тут лишнее.

2018-04-16 19:03 UTC, dsavvinov commented on src/main/java/au/xamgore/HashDict.java
> +    if (key == null || value == null) {
1. В методе интерфейса `Key` помечен как `@NotNull`, почему здесь он стал `@Nullable`?

2. Аннотация `@Nullable` на аргументах подразумевает, что я могу передавать туда `null`, что не соответствует логике метода. Надо тогда было как `@NotNull` помечать

3. Почему-то поведение не очень консистентное -- `get` обрабатывает `null`ы некоторым дефолтным образом, а `put` падает.

2018-04-16 19:03 UTC, dsavvinov commented on src/main/java/au/xamgore/HashDict.java
> +  private Pair<K, V> createNewPair(@NotNull K key, List<Pair<K, V>> bucket) {
Извиняюсь за занудство, но это `createAndPutNewPair`, а не `createNewPair` :) Иначе код местами читается очень странно -- например, в 79ой строке кажется, что мы просто создали новую пару и сразу ее выдали, а на самом деле мы ее создали, положили в бакет, да еще и заэкспанидились при необходимости.

2018-04-16 19:03 UTC, dsavvinov commented on src/main/java/au/xamgore/HashDict.java
> +    Pair<K, V> dead = getPair(key, bucket).orElse(null);
Вот такие вот пассажи заставляют задуматься -- действительно ли `Optional` тут так полезен и нужен, и стало ли хуже, если бы `getPair` просто возвращал nullable значение.

2018-04-16 19:03 UTC, dsavvinov commented on src/main/java/au/xamgore/HashDict.java
> +    return getPair(key, bucket)
А почему здесь не воспользоваться перегрузкой без `bucket`?

2018-04-16 19:03 UTC, dsavvinov commented on src/main/java/au/xamgore/HashDict.java
> +  private Pair<K, V> createNewPair(@NotNull K key, List<Pair<K, V>> bucket) {
P.S. А вообще лично мне кажется, что если без этого метода код станет лучше -- например, тогда код в `put` будет симметричным коду в `remove` (в нем тоже возникнет `size++` и `expand()`, противоположно `size--` и `shrink()`)

2018-04-16 19:03 UTC, dsavvinov commented on src/main/java/au/xamgore/HashDict.java
> +    if (getLoadFactor() > loadFactor)
Minor: Я бы `loadFactor` назвал как-нибудь по-другому, типа `maxLoadFactor`, или что-то такое, иначе эта строка очень странно выглядит

2018-04-16 19:03 UTC, dsavvinov commented on src/main/java/au/xamgore/HashDict.java
> +      changeBucketsCount(count, true);
Это условие может выполниться, даже если `count == INITIAL_BUCKETS_COUNT`. Учитывая, что изменить размер меньше `INITIAL_BUCKETS_COUNT` нельзя, то вот такой код будет постоянно копировать-перекладывать бакеты с места на место:
```
for (int i = 0; i < 100; ++i) {
    d.put(42, "")
    d.remove(42) // bogus re-hash on each iteration
}
```

Это очень плохо, надо исправлять

2018-04-16 19:03 UTC, dsavvinov commented on .idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Эти и другие файлы из `.idea` лучше тоже игнорить, т.к. проект и так на грэдле. У меня вот например почему-то плохо проект открывается, приходится переимпортировать.

2018-04-18 13:39 UTC, xamgore commented on .idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Я не очень хорошо разбираюсь в структуре и назначении каждого файла из `.idea`, но мне кажется, что игнорировать всю директорию — тоже плохая идея (я так делал, не очень понравилось). Я использую шаблоны https://github.com/github/gitignore, в частности Gradle, Maven, JetBrains, Java и предполагаю, что чуваки по каким-то разумным причинам не стали прятать `modules.xml`.

Добавил `.idea/.modules.xml` в `.gitignore`, чтобы не приходилось переимпортировать.

2018-04-18 13:53 UTC, xamgore commented on src/main/java/au/xamgore/HashDict.java
> +    return getPair(key, bucket)
Мне мгновение показалось, что плохо вызывать одну и ту же функцию `getBucket` два раза. Хотя она и за `O(1)` работает.

```java
  private Optional<Pair<K, V>> getPair(@NotNull K key) {
    return getPair(key, getBucket(key));
  }
```

2018-04-18 14:07 UTC, xamgore commented on src/main/java/au/xamgore/HashDict.java
> +    Pair<K, V> dead = getPair(key, bucket).orElse(null);
`Optional` безусловно полезен, потому что делает функции тотальными и не даёт возможности случайно прострелить себе ногу. Удобно применять функции к значениям в `Optional`.

Другое дело, что ребята из Oracle решили сделать так, что `get` бросает `NullPointerException` и вот это уже очень грустно.

Касательно этой строки — метод используется из соображений переиспользования кода и уменьшения сравнений на null. Но попробую применить рекомендацию.

2018-04-18 14:38 UTC, dsavvinov commented on src/main/java/au/xamgore/HashDict.java
> +    Pair<K, V> dead = getPair(key, bucket).orElse(null);
Я бы не сказал, что в остальных двух местах мне очень уж нравится.

Если что, ни изначальный комментарий, ни этот, не являются побуждением что-то переделывать, к тому же это все мое субъективное мнение. Это скорее просто была информация к размышлению :)

2018-04-18 17:24 UTC, xamgore commented on src/main/java/au/xamgore/HashDict.java
> +  private Pair<K, V> createNewPair(@NotNull K key, List<Pair<K, V>> bucket) {
Удалил вот это всё.

2018-04-18 18:04 UTC, xamgore commented on src/main/java/au/xamgore/HashDict.java
> +      changeBucketsCount(count, true);
Исправил, сейчас должно быть ок.

2018-04-18 18:04 UTC, xamgore commented on src/main/java/au/xamgore/HashDict.java
> +    if (getLoadFactor() > loadFactor)
Не смог придумать ему название, так что удалил метод :)

2018-04-18 20:35 UTC, xamgore commented on src/main/java/au/xamgore/HashDict.java
> +    if (oldBuckets == null || !moveOld) {
Он там не был лишним (наверное), потому что его вызывал `clear()` при инициализации экземпляра класса. Но я удалил эту фигню и написал почище всё.

2018-04-18 20:38 UTC, xamgore commented on src/main/java/au/xamgore/HashDict.java
> +    if (key == null || value == null) {
Я скорее всего не выспался, потому что хз, почему так сделал. Это, конечно, глупость большая. Переписал, но оставил `@Nullable` у параметра `key`. Реализация более свободная, нежели интерфейс, так что всё в порядке. Теперь и `get` и `put` обрабатывает `null`.

2018-04-18 20:45 UTC, xamgore commented on src/main/java/au/xamgore/HashDict.java
> +    Pair<K, V> dead = getPair(key, bucket).orElse(null);
Я понял, почему я хотел там тотальность. В бакете могли отсутствовать какие-нибудь значения + были `nullable` ключи, и это меня навело на мысль, что можно воспользоваться `Optional`. Оказалось, что лучше вынести пару с `key = null` в отдельное поле, и работать там. Тогда удобным образом можно отслеживать с помощью `== null` наличие пары в бакете, и устраивать разное поведение в `put` и `remove`.

2018-04-18 20:51 UTC, xamgore commented
1. В общем, я приношу большие извинения, что это вообще пришлось читать. 

2. Я переписал большую часть, так что теперь по идее читаться должно гораздо легче. 
3. Подправил хеширование, хотя идея осталась та же: хотим чтобы в каждом бакете было примерно одинаковое количество элементов. 

4. Сделал интересный момент с `nullKeyInstance`.

5. Пофиксил свой `Math.abs(hash % size)`, он выдавал `IndexOutOfBoundsException`, если сделать объект, у которого хэш равен `Integer.MIN_VALUE`, что довольно забавно :sweat_smile:

2018-04-23 08:00 UTC, dsavvinov approved these changes
Вторая итерация действительно просто отличная, придраться абсолютно не к чему. Сразу бы так, и были бы твердые 10б :)

9б, зачтено

2018-05-26 12:00 UTC, closed without merging