Java05. ДЗ 04, Стребежев Игорь
xamgore/au-java-homework pull request #5
Opened 2018-04-19 21:45 UTC by xamgore

2018-05-21 09:05 UTC, dsavvinov requested changes
`foldr` надо бы поправить

2018-05-21 09:05 UTC, dsavvinov commented on src/main/java/spbau/Collections.java
> +  public static <T> Collection<T> takeUntil(Predicate<? super T> predicate,
Лайк за корректное название метода :)

2018-05-21 09:05 UTC, dsavvinov commented on src/main/java/spbau/Collections.java
> +  public static <A, B> B foldr(Function2<? super A, ? super B, ? extends B> func, B zero, Collection<? extends A> coll) {
Что-то с этим foldr не так. В итоге `func` в первый раз будет вызвана на первом элементе `coll`, а не на последнем.

2018-05-22 16:49 UTC, xamgore commented on src/main/java/spbau/Collections.java
> +  public static <A, B> B foldr(Function2<? super A, ? super B, ? extends B> func, B zero, Collection<? extends A> coll) {
Предательский addLast, надо addFirst (это дичь, конечно). Добавил тест, исправил.

2018-05-22 18:17 UTC, dsavvinov commented
9б, зачтено

2018-05-22 18:17 UTC, dsavvinov approved these changes

2018-05-23 18:20 UTC, closed without merging